controllers:
    resource: ../src/Controller/
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

inscription:
    path: /inscription
    controller: App\Controller\RegistrationController::inscription

inscription_success:
    path: /inscription/success
    controller: App\Controller\RegistrationController::inscriptionSuccess
